"""ExtractionEnvelope — container for extraction results + provider metadata."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from aurora.extraction.candidates import Candidate


@dataclass(frozen=True)
class ProviderMetadata:
    """Metadata about the extraction provider that generated results."""

    name: str
    version: str
    deterministic_mode: bool
    case_id: str = ""
    extra: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class ExtractionEnvelope:
    """Immutable container for extraction candidates and provider metadata.

    Generated by an ExtractionProvider from a ContextWindow.
    All candidates reference units within the originating context window.
    """

    candidates: tuple[Candidate, ...]
    provider_metadata: ProviderMetadata
    warnings: tuple[str, ...] = ()
    errors: tuple[str, ...] = ()

    @property
    def candidate_count(self) -> int:
        return len(self.candidates)

    def candidates_by_type(self, candidate_type: type) -> list[Candidate]:
        """Return all candidates matching the given type."""
        return [c for c in self.candidates if isinstance(c, candidate_type)]

    @property
    def entities(self) -> list[Candidate]:
        from aurora.extraction.candidates import EntityCandidate

        return self.candidates_by_type(EntityCandidate)

    @property
    def data_points(self) -> list[Candidate]:
        from aurora.extraction.candidates import DataPointCandidate

        return self.candidates_by_type(DataPointCandidate)

    @property
    def claims(self) -> list[Candidate]:
        from aurora.extraction.candidates import ClaimCandidate

        return self.candidates_by_type(ClaimCandidate)

    @property
    def evidences(self) -> list[Candidate]:
        from aurora.extraction.candidates import EvidenceCandidate

        return self.candidates_by_type(EvidenceCandidate)

    @property
    def fact_candidates(self) -> list[Candidate]:
        from aurora.extraction.candidates import FactCandidate

        return self.candidates_by_type(FactCandidate)

    def __repr__(self) -> str:
        return (
            f"ExtractionEnvelope(provider={self.provider_metadata.name!r}, "
            f"candidates={self.candidate_count})"
        )
