"""Object registry, version-aware parsing, and JSON Schema export."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from pydantic import TypeAdapter

from .models import (
    AuroraObject,
    Claim,
    ContentUnit,
    DataPoint,
    Document,
    Entity,
    Event,
    Evidence,
    Fact,
    Feedback,
    Insight,
    KnowledgeObject,
    OutputArtifact,
    PersonalOpinion,
    ProcessingRun,
    Relation,
    Source,
    TimelineEntry,
)
from .models.common import BaseObject, SCHEMA_VERSION
from .models.enums import ObjectType
from .schema_migrations import upgrade_payload

MODEL_REGISTRY: dict[ObjectType, type[BaseObject]] = {
    ObjectType.SOURCE: Source,
    ObjectType.DOCUMENT: Document,
    ObjectType.CONTENT_UNIT: ContentUnit,
    ObjectType.ENTITY: Entity,
    ObjectType.EVENT: Event,
    ObjectType.DATA_POINT: DataPoint,
    ObjectType.CLAIM: Claim,
    ObjectType.EVIDENCE: Evidence,
    ObjectType.FACT: Fact,
    ObjectType.KNOWLEDGE_OBJECT: KnowledgeObject,
    ObjectType.RELATION: Relation,
    ObjectType.TIMELINE_ENTRY: TimelineEntry,
    ObjectType.INSIGHT: Insight,
    ObjectType.PERSONAL_OPINION: PersonalOpinion,
    ObjectType.OUTPUT_ARTIFACT: OutputArtifact,
    ObjectType.FEEDBACK: Feedback,
    ObjectType.PROCESSING_RUN: ProcessingRun,
}

AURORA_OBJECT_ADAPTER = TypeAdapter(AuroraObject)


def parse_object(payload: dict[str, Any]) -> BaseObject:
    """Parse V1.0 or V1.1 payload into the current V1.1 domain model."""

    current_payload = upgrade_payload(payload, target_version=SCHEMA_VERSION)
    raw_type = current_payload.get("object_type")
    if raw_type is None:
        raise ValueError("payload is missing object_type")
    try:
        object_type = ObjectType(raw_type)
    except ValueError as exc:
        raise ValueError(f"unsupported object_type: {raw_type}") from exc
    return MODEL_REGISTRY[object_type].model_validate(current_payload)


def export_json_schemas(
    output_dir: Path,
    *,
    schema_version: str = SCHEMA_VERSION,
) -> list[Path]:
    """Export schemas for the current domain model.

    V1.0 schemas are frozen assets and must not be regenerated by V1.1 code.
    """

    if schema_version != SCHEMA_VERSION:
        raise ValueError(
            f"current models can only export schema_version={SCHEMA_VERSION}"
        )

    output_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for object_type, model_class in MODEL_REGISTRY.items():
        schema = model_class.model_json_schema()
        schema["$id"] = (
            "https://aurora.local/schemas/"
            f"v{schema_version.replace('.', '_')}/"
            f"{object_type.value}.schema.json"
        )
        target = output_dir / f"{object_type.value}.schema.json"
        target.write_text(
            json.dumps(schema, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
        written.append(target)

    registry_path = output_dir / "registry.json"
    registry_path.write_text(
        json.dumps(
            {
                "schema_version": schema_version,
                "objects": {
                    object_type.value: f"{object_type.value}.schema.json"
                    for object_type in MODEL_REGISTRY
                },
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    written.append(registry_path)
    return written


def export_root_registry(schema_root: Path) -> Path:
    """Write the multi-version schema registry without changing version assets."""

    schema_root.mkdir(parents=True, exist_ok=True)
    target = schema_root / "registry.json"
    target.write_text(
        json.dumps(
            {
                "latest": SCHEMA_VERSION,
                "versions": {
                    "1.0": "v1/registry.json",
                    "1.1": "v1_1/registry.json",
                },
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    return target


def main() -> None:
    parser = argparse.ArgumentParser(description="Export Aurora JSON Schemas")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("schemas/v1_1"),
        help="V1.1 schema output directory",
    )
    parser.add_argument(
        "--schema-root",
        type=Path,
        default=Path("schemas"),
        help="Root directory for the multi-version registry",
    )
    args = parser.parse_args()
    written = export_json_schemas(args.output)
    export_root_registry(args.schema_root)
    print(f"Exported {len(written) - 1} object schemas to {args.output}")


if __name__ == "__main__":
    main()
